<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="el-gr" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta property="og:image" content="<?php echo Zend_Registry::get('siteurl') ?>images/fb_like.jpg"/>


<?php
    
        echo $this->headTitle();
        echo $this->headMeta();
		$this->headLink()->appendStylesheet('/js/fancybox/jquery.fancybox-1.3.4.css');
        $this->headLink()->appendStylesheet('/style/style.css');
		$this->headLink()->appendStylesheet('/style/custom.css');
		$this->headLink()->appendStylesheet('/js/jqtransform/jqtransform.css');
				
        echo $this->headLink(); 
		$this->headScript()->appendFile('/js/fancybox/jquery.fancybox-1.3.4.js'); 
        $this->headScript()->appendFile('/js/jqtransform/jquery.jqtransform.js');
		$this->headScript()->appendFile('/js/cufon-yui.js');
		$this->headScript()->appendFile('/js/Futura_500.font.js'); 
		echo $this->headScript();
?>
	<!--[if IE 6]>
			<link href="/style/ie6only.css" media="screen" rel="stylesheet" type="text/css" />
	<![endif]-->

<?php echo $this->render("/page/googlecode.phtml"); ?>
</head>
<body>
	<div id="wrapper">    	
		<!-- Header HTML -->
		<?php echo $this->render("/page/header.phtml"); ?>	
		
		<div id="shadow">
			<div id="steps">
				<img src="/images/Artwork-1.jpg"/>
				<!-- <h2><span><?php echo $this->lang[2]; ?></span></h2> -->
				<ul id="steps_cols" class="cols">
					<li id="step1">
						<h3><span><?php echo $this->lang[3]; ?></span></h3>
						<p><?php echo  $this->lang[4]; ?></p>
					</li>

					<li id="step2">
						<h3><span><?php echo $this->lang[5]; ?></span></h3>
						<p><?php echo $this->lang[6]; ?></p>
					</li>

					<li id="step3">
						<h3><span><?php echo $this->lang[7]; ?></span></h3>
						<p><?php echo $this->lang[8]; ?></p>
					</li>
				</ul>
			</div>
			<?php echo $this->layout()->content ?> 
			<div id="moreInfoIndex" class="clearfix">
				<div class="left">
					<ul>
						<li>
							<h2><span><?php echo $this->lang[541]; ?></span></h2>
							<a href="<?php echo $this->seoUrl('/sitemap/doctor');?>"><?php echo $this->lang[49]; ?></a>
							<a href="<?php echo $this->seoUrl('/sitemap/city');?>"><?php echo $this->lang[50]; ?></a>
						</li>
						<li>
							<h2>&nbsp;</h2>
							<a href="<?php echo $this->seoUrl('/sitemap/specialty');?>"><?php echo $this->lang[51]; ?></a>
							<a href="<?php echo $this->seoUrl('/sitemap/insurance-company');?>"><?php echo $this->lang[52]; ?></a>
						</li>
						<li>
							<h2>&nbsp;</h2>
							<a href="<?php echo $this->seoUrl('/sitemap/zip-list');?>"><?php echo $this->lang[53]; ?></a>
							<a href="<?php echo $this->seoUrl('/sitemap/reason-for-visit');?>"><?php echo $this->lang[54]; ?></a>
						</li>
					</ul>
				</div>
				<a href="/contact-us" class="docLink right"><img src="/images/signup.jpg"/></a>
			</div>
		</div>		
	<!-- footer HTML -->
	<?php echo $this->render("/page/footer.phtml"); ?> 
  	</div>
</body>
</html>
