<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml" lang="en-gb" xmlns:fb="http://www.facebook.com/2008/fbml">

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<?php
        echo $this->headTitle();
        echo $this->metaImage();
        echo $this->headMeta();
		$this->headLink()->appendStylesheet('/js/fancybox/jquery.fancybox-1.3.4.css');
        $this->headLink()->appendStylesheet('/style/style.css');
		if($this->controllerName=='profile'){
			$this->headLink()->appendStylesheet('/style/profile.css');
		} else if($this->controllerName=='search'){
			$this->headLink()->appendStylesheet('/style/list.css');
			$this->headLink()->appendStylesheet('/style/paginator.css');
		} else if($this->controllerName=="appointment") {
			$this->headLink()->appendStylesheet('/style/general_pages.css');
		}
		$this->headLink()->appendStylesheet('/style/custom.css');
		$this->headLink()->appendStylesheet('/js/jqtransform/jqtransform.css');
        echo $this->headLink();
		$this->headScript()->appendFile('/js/fancybox/jquery.fancybox-1.3.4.js');
		$this->headScript()->appendFile('/js/jqtransform/jquery.jqtransform.js');
		$this->headScript()->appendFile('/js/cufon-yui.js');
		$this->headScript()->appendFile('/js/Futura_500.font.js'); 
        echo $this->headScript();

        ?>
		<!--[if IE 6]>
			<link href="/style/ie6only.css" media="screen" rel="stylesheet" type="text/css" />
		<![endif]-->
<?php echo $this->render("/page/googlecode.phtml"); ?>

</head>

<body>
	<div id="wrapper">      	
		<!-- Header HTML -->
		<?php echo $this->render("/page/header.phtml"); ?>		
		<div id="shadow" class="clearfix">
			<!-- Content Area HTML -->
			<?php echo $this->layout()->content ?>			
		
			<?php if($this->controllerName=='search' && $this->paginator != null) { ?>
		<div id="pagination">
			<div>
				<?php if($this->prevUrl !=''){
						echo '<a class="prevPageBtn up" href="/search?'.$this->prevUrl.'">&nbsp;<span>Previous</span></a>';
					}?> Page <span class="selected_pag"><?php echo $this->paginator->getCurrentPageNumber(); ?></span> from <span class="selected_pag"><?php echo $this->paginator->count(); ?></span>
		<?php if($this->nextUrl !=''){
						echo '<a class="nextPageBtn up" href="'.$this->seoUrl('/search?'.$this->nextUrl).'">&nbsp;<span>Next</span></a>';
					}?>
				
			</div>
		</div>	
		<?php } //end pagination if ?>
		</div>
		<!-- footer HTML -->
		<?php echo $this->render("/page/footer.phtml"); ?> 
  	</div>
</body>
</html>

